# Generated by Django 4.0 on 2023-02-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblColor',
            },
        ),
    ]
