# Generated by Django 4.1 on 2023-03-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order_shippingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
